spring.application.name=bitproject

#### database details##
##Driver name:Server name: host name:port no/database name
spring.datasource.url=jdbc:MYSQL://localhost:3306/myproject24
spring.datasource.username=root
spring.datasource.password=root@1234

#if you want to change port, use this
#server.port=
